version: "3"

services:
  db: 
    image: postgres:16.1
    ports:
      - 5432:5432
    volumes:
      - ./psql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=greenlight
      - POSTGRES_DB=greenlight
      - POSTGRES_PASSWORD=greenlight
